debug:
    logging:
        configuration: debug
        initialization: debug
        collision_space: info
        kinematics: info
        hashmanager: info
        search: info
        motionprimitives: info
        heuristics: debug
